In [5]:
import numpy as np

def gradient_descent(gradient, start, learn_rate, n_iter=10, tolerance=1e-06):
    vector = start
    for _ in range(n_iter):
        diff = -learn_rate * gradient(vector)
        if np.all(np.abs(diff) <= tolerance):
            break
        vector += diff.astype(vector.dtype)  # Explicitly convert diff to the same data type as vector
    return vector

# Ví dụ với hàm f(x, y) = x^2 + y^2
gradient = lambda v: 2 * v  # Gradient của hàm số
start = np.array([5, 5])  # Điểm bắt đầu
learn_rate = 0.1  # Learning rate

minimum = gradient_descent(gradient, start, learn_rate)
print("Cực tiểu của hàm số là tại điểm:", minimum)

Cực tiểu của hàm số là tại điểm: [4 4]


In [6]:
import numpy as np

def simulated_annealing(energy_func, initial_state, temp, reanneal, maxsteps=1000):
    state = initial_state
    scale = np.sqrt(temp)
    for step in range(maxsteps):
        fraction = step / float(maxsteps)
        T = temp * np.exp(-fraction)
        new_state = state + scale * np.random.standard_normal(state.shape)
        new_energy = energy_func(new_state)
        old_energy = energy_func(state)
        if np.random.rand() < np.exp((old_energy - new_energy) / T):
            state, old_energy = new_state, new_energy
        if step % reanneal == 0:
            scale = np.sqrt(T)
    return state

In [7]:
from pyeasyga import pyeasyga

# setup data
data = [('pear', 50), ('apple', 35), ('banana', 40)]

ga = pyeasyga.GeneticAlgorithm(data)        # initialise the GA with data
ga.population_size = 200                    # increase population size to 200 (default value is 50)

# define a fitness function
def fitness(individual, data):
    fitness = 0
    if individual.count(1) == 2:
        for (selected, (fruit, profit)) in zip(individual, data):
            if selected:
                fitness += profit
    return fitness

ga.fitness_function = fitness               # set the GA's fitness function
ga.run()                                    # run the GA
print(ga.best_individual())                 # print the GA's best solution

(90, [1, 0, 1])


In [8]:
from pyswarm import pso

# Define the objective (to be minimized)
def weight(x, *args):
    H, d, t = x
    B, rho, E, P = args
    return rho*2*np.pi*d*t*np.sqrt((B/2)**2 + H**2)

# Setup the constraint functions
def yield_stress(x, *args):
    H, d, t = x
    B, rho, E, P = args
    R = np.sqrt((B/2)**2 + H**2)
    return (P*R)/(2*t*np.pi*R*d)

def buckling_stress(x, *args):
    H, d, t = x
    B, rho, E, P = args
    R = np.sqrt((B/2)**2 + H**2)
    return (np.pi**2*E*(d**2 + t**2))/(8*(R**2))

def constraints(x, *args):
    strs = yield_stress(x, *args)
    buck = buckling_stress(x, *args)
    return [200 - strs, buck - strs]

# Define the other parameters
B = 60  # inches
rho = 0.3  # lb/in^3
E = 30000  # kpsi (1000-psi)
P = 66  # kip (1000-lbs, force)
args = (B, rho, E, P)

# Define the lower and upper bounds for H, d, t, respectively
lb = [10, 1, 0.01]
ub = [30, 3, 0.25]

xopt, fopt = pso(weight, lb, ub, f_ieqcons=constraints, args=args)

Stopping search: Swarm best objective change less than 1e-08


In [5]:
f = x.T*A*x + b.T*x + c

c:\Users\karin\AppData\Local\Programs\Python\Python39\lib\site-packages\cvxpy\expressions\expression.py:621: UserWarning: 
This use of ``*`` has resulted in matrix multiplication.
Using ``*`` for matrix multiplication has been deprecated since CVXPY 1.1.
    Use ``*`` for matrix-scalar and vector-scalar multiplication.
    Use ``@`` for matrix-matrix and matrix-vector multiplication.
    Use ``multiply`` for elementwise multiplication.
This code path has been hit 1 times so far.

  warnings.warn(msg, UserWarning)


ValueError: Incompatible dimensions (1, 20) (30, 20)

In [21]:
import cvxpy as cp
import numpy as np

# Problem data.
m = 30
n = 20
np.random.seed(1)
A = np.random.randn(m, n)
b = np.random.randn(m)

# Construct the problem.
x = cp.Variable(n)
objective = cp.Minimize(cp.sum_squares(A @ x - b))
constraints = [0 <= x, x <= 10]
prob = cp.Problem(objective, constraints)

result = prob.solve()

print(x.value)
print(constraints[0].dual_value)

[-1.79109255e-19  2.85112420e-02  2.79973443e-19  3.37658729e-20
 -2.72802663e-19  1.49285011e-01 -9.94082533e-20  8.35373900e-20
  2.46718649e-01  5.78224144e-01 -4.03739463e-19  1.01242860e-03
 -9.28486180e-20  2.26767464e-01 -1.58813678e-19 -8.97232272e-20
 -1.22145729e-19 -1.51509428e-19  1.12060672e-19 -3.48318635e-19]
[ 2.50938945  0.          2.78354615  1.79425782 13.08579183  0.
  0.73716363  3.35344995  0.          0.          8.93825054  0.
  7.02955161  0.          4.71068649  3.18873635  2.06090107 10.08166738
  3.0481157   8.53268239]


In [ ]:
d

In [22]:
import numpy as np

# Generate a random positive definite matrix
n = 3  # Size of the matrix
A = np.random.rand(n, n)
A = np.dot(A, A.T)

print("Positive definite matrix:")
print(A)


Positive definite matrix:
[[0.51801047 0.50328441 0.57672306]
 [0.50328441 1.17207541 0.60622443]
 [0.57672306 0.60622443 0.75546569]]
